spring:
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONN_STR}
      discovery:
        enabled: true
        register: true
        root: /testapp
        prefer-ip-address: true
      dependencies:
        readApi:
          path: /readapi
          loadBalancerType: ROUND_ROBIN
          version: v1
          required: true
        writeApi:
          path: /writeapi
          loadBalancerType: ROUND_ROBIN
          version: v1
          required: true

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

server:
  port: 8080
