spring:
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONN_STR}
      discovery:
        enabled: true
        register: true
        root: /testapp
        prefer-ip-address: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id
  redis:
    cluster:
      nodes: ${REDIS_HOST}
      max-redirects: 3
    password: ${REDIS_PASSWORD}
server:
  port: 8080
jpa:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  dialect: org.hibernate.dialect.MySQL5Dialect
  ddlAuto: none
