spring:
  application:
    name: readapi
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONN_STR}
      discovery:
        enabled: true
        register: true
        root: /testapp
        prefer-ip-address: true
  redis:
    cluster:
      nodes: ${REDIS_HOST}
      max-redirects: 3
    password: ${REDIS_PASSWORD}
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

server:
  port: 8080

jpa:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  dialect: org.hibernate.dialect.MySQL5Dialect
  ddlAuto: none
